#!/usr/bin/env python3
"""Regenerate ipscanner/data/oui_builtin.py from the bundled IEEE registry.

The built-in table is the fallback used when the gzipped registry is missing,
so it has to be correct. Hand-maintaining it is how you end up with a prefix
attributed to the wrong vendor, so instead we keep a curated list of *which*
prefixes matter and let IEEE supply the names.

    python tools/rebuild_builtin_oui.py
"""

from __future__ import annotations

import csv
import gzip
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

REGISTRY = ROOT / "ipscanner" / "data" / "oui.csv.gz"
TARGET = ROOT / "ipscanner" / "data" / "oui_builtin.py"

HEADER = '''"""Built-in OUI prefixes (first three MAC octets) to vendor names.

A curated fallback used when the bundled IEEE registry cannot be read. Every
name here comes straight from the IEEE registry - this file is generated by
tools/rebuild_builtin_oui.py, so do not hand-edit it.

Virtualisation and single-board-computer hints live separately in
ipscanner/core/oui.py (PLATFORM_HINTS), because the useful label for
08:00:27 is "VirtualBox", not its legal registrant.
"""

from __future__ import annotations


def normalise(prefix: str) -> str:
    return "".join(ch for ch in prefix.upper() if ch in "0123456789ABCDEF")[:6]


OUI: dict[str, str] = {
'''

FOOTER = '''}

#: Kept as a distinct name for backwards compatibility; the table above is
#: already normalised, so no cleaning pass is needed.
OUI_CLEAN: dict[str, str] = OUI
'''

# Prefixes worth keeping offline: hypervisors, SBCs, and the vendors you
# actually meet on a corporate subnet.
CURATED = """
000569 000C29 001C14 005056 080027 0A0027 00155D 525400 5254AB 00163E 001C42
0242AC B827EB DCA632 E45F01 28CDC1 D83ADD 2CCF67
240AC4 30AEA4 3C71BF 5CCF7F 840D8E A020A6 ACD074 B4E62D CC50E3 ECFABC 7C9EBD
84F3EB 083AF2 349454
00000C 000142 0001C7 000A41 001121 0018BA 001B0C 002155 00259C 0050F0 6C503E
F02572 E8B748 00D0BC 506B8D 88157A E0CB1D 0004DD 001A2F
000B86 6CF37F 18645C 9C1C12 204C03 D8C7C8
0017DF 2C6BF5 5C5EAB 78FE3D F4B52F 0010DB
0009F5 00E0FC 1C1D67 283152 48DB50 5CA86A 781DBA C4072F E0247F FC48EF 00259E
0022A1
0015FF 4C5E0C 6C3B6B 744D28 B869F4 CC2DE0 DC2C6E E48D8C 2CC81B 000C42
0418D6 24A43C 44D9E7 788A20 802AA8 B4FBE4 DC9FDB F09FC2 FCECDA 74ACB9 E063DA
000FB5 001B2F 008EF2 20E52A 2C3033 44944C A040A0 C03F0E E091F5 00095B 0026F2
001E58 00265A 1CBDB9 34081F 78542E 9094E4 C8BE19 F07D68 001CF0
000AEB 14CC20 1C61B4 3C846A 50C7BF 5C63BF 6466B3 A42BB0 C46E1F E894F6 F4F26D
AC84C6
001349 00A0C5 5CE28C B0B2DC
10C37B 1C872C 2C56DC 381428 50465D 704D7B AC220B BCEE7B D850E6 F832E4 001FC6
0003C6 00090F 085B0E 704CA5 9017AC E82689 001C7F 00E02B 001B17 B40C25
001560 0017A4 001B78 002264 0025B3 1458D0 2C4138 3822D6 3C4A92 40A8F0 6CC217
9457A5 A0481C B499BA F430B9 98E7F4 00306E
000BDB 00123F 001EC9 002219 0024E8 14FEB5 18A99B 246E96 34177F 509A4C 5CF9DD
742B62 B083FE D067E5 F8BC12 F8DB88 1866DA A4BB6D
000629 00096B 001A64 00215E 5CF3FC E41F13 6CAE8B
0002B3 000E0C 001320 001B21 001E67 0024D7 3417EB 34E12D 3C9702 44032C 5CE0C5
7085C2 8C554A 94659C A0A8CD B4D5BD E4B318 F8341A 9C2976 48513B
00089B 00121C 1C6F65 3C18A0 54EE75 6C0B84 8CDCD4 A4C3F0 E85AD1
0003FF 0017FA 281878 3C8375 485073 7CED8D F01DBC 0050F2 00125A
000393 000A27 001451 001EC2 0023DF 0026B0 109ADD 14109F 24AB81 28CFE9 3451C9
40331A 4C8D79 5855CA 60FACD 68967B 7CD1C3 8C8590 98F0AB A45E60 B8E856 C82A14
D0E140 E0ACCB F0DBE2 F82793 0C4DE9
0016DB 08D42B 18227E 241B7A 34AA8B 5001BB 5CF6DC 8C71F8 A02195 C81479 E8508B
FCC734
286C07 3480B3 506583 64B473 7C1DD9 8CBEBE 9C99A0 F8A45F
001E75 0022A9 10683F 344DF7 A039F7 C4366C
001A80 0013A9 30F9ED 5453ED B4527D FC0FE6
3C5AB4 44070B 94EB2C F4F5D8 F4F5E8
0C47C9 34D270 44650D 747548 A002DC FC65DE F0272D
000E58 347E5C 5CAAFD B8E937 001788 ECB5FA
001132 00089F 0090A9 0014EE
000048 0026AB 44D884 000085 001E8F 2C9EFC 008077 008092 30055C 001BA9
00000F 0000AA 9C934E 002673 0017C8
00408C ACCC8E B8A44F 4419B6 BCAD28 18680B 586ED6 3CEF8C 4C11BF
001083 000FBB 001C06 0000BC 0001D7 0090E8
000E2E 001C10 0016B6 000424 000EC6 00E04C 001C25 8C89A5 D43D7E 4CCC6A 0019DB
"""


def main() -> int:
    if not REGISTRY.exists():
        print(f"error: {REGISTRY} is missing; run tools/update_oui.py first",
              file=sys.stderr)
        return 1

    ieee: dict[str, str] = {}
    with gzip.open(REGISTRY, "rt", encoding="utf-8", errors="ignore", newline="") as fh:
        for row in csv.reader(fh):
            if len(row) >= 2:
                ieee[row[0]] = row[1]

    wanted = sorted(set(CURATED.split()))
    resolved: dict[str, str] = {}
    missing: list[str] = []
    for prefix in wanted:
        vendor = ieee.get(prefix)
        if vendor:
            resolved[prefix] = vendor
        else:
            missing.append(prefix)

    lines = [
        f'    "{prefix}": {_quote(resolved[prefix])},'
        for prefix in sorted(resolved)
    ]
    TARGET.write_text(HEADER + "\n".join(lines) + "\n" + FOOTER, encoding="utf-8")

    print(f"Wrote {TARGET.relative_to(ROOT)}")
    print(f"  {len(resolved)} prefixes verified against the IEEE registry")
    if missing:
        print(f"  {len(missing)} dropped (not in the registry): {', '.join(missing)}")
    return 0


def _quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


if __name__ == "__main__":
    raise SystemExit(main())
